version: "3"

services:
  db:
    container_name: hcmiu_se_db
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: nguyenvandat
      MYSQL_DATABASE: banking
      MYSQL_PASSWORD: hcmiuse@14
      MYSQL_ROOT_PASSWORD: hcmiuse@14
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - "3306:3306"

volumes: 
  db_data: 



